on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet publish -c Release -o backend/api/publish -p:PublishDir=backend/api/publish --source backend/api
      - uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: false
          appdir: "backend/api/publish"
        env:
          HD_JWT_KEY: ${{secrets.JWT_KEY}}
          HD_pgconn: ${{secrets.PGCONN}}
          HD_mqttToken: ${{secrets.MQTTTOKEN}}
