on:
  push:
  workflow_dispatch:
    
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: cd backend/test && dotnet test
        env:
          JWT_KEY: ${{secrets.JWT_KEY}}
          pgconn: ${{secrets.pgconn}}
          mqttToken: ${{secrets.mqttToken}}
